### ISSUE TITLE
Config creates wrong keys

### ISSUE THREAD

**Issue by dlernstrom** [Digital-Sapphire/PyUpdater-SCP-Plugin#1]
The SCPUploader plugin appears to create wrong keys.  I can submit a pull request if you can validate the problem.

The SCPUploader has a method called init_config, which looks for config items like ssh_username and ssh_host.  However, the set_config method creates the keys as username and host.  Consequently, the config file config.pyu ends up having the wrong plugin configuration.

Additionally, I've run into two additional problems.  Nothing indicates (other than looking at the code) that I should stick my password into an environment variable called "PYU_SSH_PASSWORD".

Lastly, I received an error:
[ERROR] Server u'ernstrom.net' not found in known_hosts

Cheers,
David

**Comment by JMSwag** [comment]
@dlernstrom This plugin needs some TLC. I'd really appreciate a pull request with the fixes for the set_config method. I'll add the docs if you don't get to it first.

I'll have to investigate the error not found in known_hosts. I've found a couple similar github issues, [here](https://github.com/onyxfish/relay/issues/11) & [here](https://github.com/paramiko/paramiko/issues/46)

**Comment by JMSwag** [comment]
@dlernstrom PyUpdater 2.0.3 & PyUpdater-SCP-plugin 3.0.5 have been uploaded to pypi. Please rerun pyupdater settings --plugins scp once you update both packages.
